# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
import torch
tensor = torch.rand(7, 7)
print(tensor)

tensor([[0.5411, 0.9035, 0.1869, 0.3768, 0.0419, 0.8234, 0.9584],
        [0.8215, 0.8176, 0.0517, 0.4523, 0.2675, 0.2340, 0.4658],
        [0.1779, 0.1594, 0.1963, 0.1415, 0.9342, 0.2488, 0.0278],
        [0.8411, 0.7800, 0.9645, 0.8226, 0.7023, 0.8691, 0.6069],
        [0.5736, 0.8938, 0.7009, 0.3531, 0.1327, 0.7908, 0.6530],
        [0.7276, 0.7536, 0.6173, 0.3650, 0.1191, 0.9555, 0.6610],
        [0.3804, 0.7570, 0.6853, 0.3516, 0.0967, 0.7886, 0.6108]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
A = torch.rand(7, 7)
B = torch.rand(1, 7)
# the problem is that B n of rows and A n of columns  not matching
# so we need to transpose B
B_T = B.T
result = torch.matmul(A, B_T)
print("A shape:", A.shape)
print("B shape:", B.shape)
print("B Transposed shape:", B_T.shape)
print("Result shape:", result.shape)
print("Result:\n", result)


A shape: torch.Size([7, 7])
B shape: torch.Size([1, 7])
B Transposed shape: torch.Size([7, 1])
Result shape: torch.Size([7, 1])
Result:
 tensor([[2.4970],
        [2.0577],
        [2.0142],
        [1.6613],
        [1.9031],
        [2.4094],
        [1.4802]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
torch.manual_seed(0)
A = torch.rand(7, 7)
B = torch.rand(1, 7)
B_T = B.T
result = torch.matmul(A, B_T)
print(result, result.shape)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
torch.manual_seed(0)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(1234)
    print("CUDA seed set to 1234 ")
else:
    print("CUDA not available  (seed set only for CPU)")

CUDA seed set to 1234 



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    print(f"Device: {device}")

    torch.manual_seed(1234)


    tensor1 = torch.rand(2, 3, device=device)
    tensor2 = torch.rand(2, 3, device=device)


    print(tensor1, "\n", tensor2)

else:
    print(" CUDA not available on this device.")


Device: cuda
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0') 
 tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    print(f"Device: {device}")


    torch.manual_seed(1234)

    tensor1 = torch.rand(2, 3, device=device)
    tensor2 = torch.rand(2, 3, device=device)

    tensor2_T = tensor2.T
    result = torch.matmul(tensor1, tensor2_T)

    print(result, result.shape)

else:
    print(" CUDA not available on this device.")


Device: cuda
tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [8]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    torch.manual_seed(1234)
    tensor1 = torch.rand(2, 3, device=device)
    tensor2 = torch.rand(2, 3, device=device)
    tensor2_T = tensor2.T
    result = torch.matmul(tensor1, tensor2_T)

    max_value = result.max()
    min_value = result.min()

    print("Result Tensor:\n", result)
    print("\nMaximum value:", max_value.item())
    print("Minimum value:", min_value.item())

else:
    print("CUDA not available on this device.")


Result Tensor:
 tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

Maximum value: 0.7667766809463501
Minimum value: 0.27863210439682007


### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
if torch.cuda.is_available():
    device = torch.device("cuda") # or device = torch.cuda.device(0)
    

    torch.manual_seed(1234)
    tensor1 = torch.rand(2, 3, device=device)
    tensor2 = torch.rand(2, 3, device=device)
    tensor2_T = tensor2.T
    result = torch.matmul(tensor1, tensor2_T)

    max_index = result.argmax()
    min_index = result.argmin()

   
    max_coords = torch.unravel_index(max_index, result.shape)
    min_coords = torch.unravel_index(min_index, result.shape)

    print("Result Tensor:\n", result)
    print(f"\nMax Value: {result.max().item()} at index {max_coords}")
    print(f"Min Value: {result.min().item()} at index {min_coords}")

else:
    print("CUDA not available on this device.")


Result Tensor:
 tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

Max Value: 0.7667766809463501 at index (tensor(0, device='cuda:0'), tensor(1, device='cuda:0'))
Min Value: 0.27863210439682007 at index (tensor(0, device='cuda:0'), tensor(0, device='cuda:0'))



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
torch.manual_seed(7)
tensor1 = torch.rand(1, 1, 1, 10)
tensor2 = tensor1.squeeze()

print(tensor1, tensor1.shape)
print(tensor2, tensor2.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
